version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum install -y unzip wget curl
      - curl -O https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - yum install -y python3-pip
      - pip3 install ansible
      - ansible --version
  pre_build:
    commands:
      - echo "Pre-build phase complete."
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve
      - ansible-playbook -i hosts splunk_setup.yml --ssh-common-args='-o StrictHostKeyChecking=no'
artifacts:
  files:
    - '**/*'
