version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Downloading tfvars from S3...
      - aws s3 cp s3://splunk-deployment-test/$TFVARS_S3_KEY terraform.tfvars
      - export STATE_KEY="splunk/states/terraform-$(date +%Y%m%d%H%M%S).tfstate"
      - cat <<EOF > backend.tf.json
{
  "terraform": {
    "backend": {
      "s3": {
        "bucket": "splunk-deployment-test",
        "key": "$STATE_KEY",
        "region": "us-east-1",
        "encrypt": true
      }
    }
  }
}
EOF
  build:
    commands:
      - terraform init -backend-config=backend.tf.json
      - terraform apply -var-file=terraform.tfvars -auto-approve
