version: 0.2

cache:
  paths:
    - /root/.cache/pip
    - /root/.ansible
    - /root/.terraform
    - key/

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install ansible
      - yum install -y unzip wget
      - curl -fsSL https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/hashicorp.repo
      - yum install -y terraform
  pre_build:
    commands:
      - echo "Pre-build phase complete."
  build:
    commands:
      - chmod +x scripts/check_key.sh
      - terraform init
      - terraform apply -auto-approve
      - chmod 600 key/*.pem
      - ansible-playbook -i hosts splunk_setup.yml --ssh-common-args='-o StrictHostKeyChecking=no'
  post_build:
    commands:
      - echo "Deployment Completed Successfully!"
