version: 0.2

cache:
  paths:
    - /root/.cache/pip
    - /root/.ansible
    - /root/.terraform
    - key/

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install ansible
      - yum install -y unzip wget
      # Directly download terraform binary
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Pre-build phase complete."
  build:
    commands:
      - chmod +x scripts/check_key.sh
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Deployment Completed Successfully!"
